imports:
    - { resource: config_dev.yml }
    - { resource: parameters.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        host:     localhost
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~
