<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domain extends \AppBundle\Entity\Domain implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'domain', 'domains', 'hrefs', 'isWWW', 'topDomains'];
        }

        return ['__isInitialized__', 'id', 'domain', 'domains', 'hrefs', 'isWWW', 'topDomains'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Domain $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$domain]);

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomains($domains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomains', [$domains]);

        return parent::setDomains($domains);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomains', []);

        return parent::getDomains();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrefs($hrefs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrefs', [$hrefs]);

        return parent::setHrefs($hrefs);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrefs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrefs', []);

        return parent::getHrefs();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsWWW($isWWW)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsWWW', [$isWWW]);

        return parent::setIsWWW($isWWW);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsWWW()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsWWW', []);

        return parent::getIsWWW();
    }

    /**
     * {@inheritDoc}
     */
    public function addTopDomain(\AppBundle\Entity\TopDomains $topDomain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTopDomain', [$topDomain]);

        return parent::addTopDomain($topDomain);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTopDomain(\AppBundle\Entity\TopDomains $topDomain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTopDomain', [$topDomain]);

        return parent::removeTopDomain($topDomain);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopDomains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopDomains', []);

        return parent::getTopDomains();
    }

}
